name: med_research_assistant
description: "A secure offline-first medical research data collection app for doctors and researchers"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Local Database (Encrypted)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

  # Security & Authentication
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.2.2

  # Image Handling
  image_picker: ^1.1.2
  camera: ^0.10.6
  path: ^1.9.0

  # Data Export
  csv: ^6.0.0
  share_plus: ^9.0.0
  permission_handler: ^11.3.1

  # UI/UX
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.20.0
  uuid: ^4.4.0
  shared_preferences: ^2.5.3
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1
  flutter_secure_storage_windows: ^3.1.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  # Fonts can be added here if needed
